# https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/configuration_reference.md
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Acme\UserBundle\Entity\User
    from_email:
        address:        %email_sender_address%
        sender_name:    %email_sender_name%
    registration:
        confirmation:
            enabled:    false # change to true for required email confirmation
            from_email:
                address:        %email_sender_address%
                sender_name:    %email_sender_name%
    resetting:
        email:
            # template: AcmeDemoBundle:User:resetting.email.html.twig
            from_email:
                address:        %email_sender_address%
                sender_name:    %email_sender_name%

