acme_user:
    resource: "@AcmeUserBundle/Controller/"
acme_publication:
    resource: "@AcmePublicationBundle/Controller/"
    type:     annotation
    prefix:   /
acme_log_entry:
    resource: "@AcmeLogEntryBundle/Controller/"
    type:     annotation
    prefix:   /
#fosuser routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"