#app/routing_rest.yml
rest_publications:
  type : rest
  resource: "@AcmePublicationBundle/Resources/config/routing_rest.yml"
rest_users:
  type : rest
  resource: "@AcmeUserBundle/Resources/config/routing_rest.yml"
