acme_user:
    resource: "@AcmeUserBundle/Controller/"
acme_publication:
    resource: "@AcmePublicationBundle/Controller/"
    type:     annotation
    prefix:   /
acme_log_entry:
    resource: "@AcmeLogEntryBundle/Controller/"
    type:     annotation
    prefix:   /