services:
    publication.listener.resolver:
        class: Acme\PublicationBundle\Entity\Listener\PublicationListener
        arguments:
            - @service_container
        tags:
            - { name: doctrine.orm.entity_listener, event: preRemove }